Repository dssaha/new-web-project-, pull requests merged in 2022-10, with the labels that each got.

#2 Create script.js
  Movie Rating App/script.js
Labels: good first issue, Hacktoberfest2022

#4 Create style.css
  Movie Rating App/style.css
Labels: good first issue, Hacktoberfest2022, hacktoberfest-accepted

#5 Create index.html
  Movie Rating App/index.html
Labels: Hacktoberfest2022, hacktoberfest-accepted

#6 Create social_business.html
  webpage/social_business.html
Labels: Hacktoberfest2022, hacktoberfest-accepted

#8 Create pmindx.html
  prasun/pmindx.html
Labels: Hacktoberfest2022, hacktoberfest-accepted

#9 Create pagehs.css
  prasun/pagehs.css
Labels: Hacktoberfest2022, hacktoberfest-accepted

#10 Create pagehs.js
  prasun/pagehs.js
Labels: Hacktoberfest2022, hacktoberfest-accepted
